CREATE SCHEMA ceneo;

CREATE TABLE categories ( 
	category_id          integer  PRIMARY KEY,
	name                 varchar(100)  unique not NULL,
	parent_category      integer,
	min_age              integer DEFAULT 0,
	CONSTRAINT fk_categories_categories FOREIGN KEY ( parent_category ) REFERENCES categories( category_id ) on delete cascade
 );

CREATE SEQUENCE seq_categories_id INCREMENT BY 1 START WITH 1;

INSERT INTO categories VALUES
(nextval('seq_categories_id'), 'wyposazenie', null, null),
(nextval('seq_categories_id'), 'meble', 1, null),
(nextval('seq_categories_id'), 'krzesla', 2, null),
(nextval('seq_categories_id'), 'szafy', 2, null),
(nextval('seq_categories_id'), 'szafki kuchenne', 4, null),
(nextval('seq_categories_id'), 'jedzenie', null, null),
(nextval('seq_categories_id'), 'napoje', 6, null),
(nextval('seq_categories_id'), 'alkohol', 7, 18);


CREATE TABLE customers ( 
	customer_id          serial  PRIMARY KEY,
	login                varchar(50) unique not NULL,
	"password"           varchar(200) not NULL,
	age                  integer,
	"location"           varchar(50)  
 );

CREATE SEQUENCE seq_customer_id INCREMENT BY 1 START WITH 1;

INSERT INTO customers VALUES
('a','a',1,'Krakow'),
('b','b',1,'Katowice'),
('c','c',20,'Warszawa'),
('d','d',25,'Krakow');

CREATE TABLE discounts ( 
	discount_id          integer  PRIMARY KEY,
	date_from            date not NULL,
	date_to              date,
	percent              numeric(4,2) DEFAULT 0, 
	CHECK (date_from < date_to),
	CHECK (percent >=0)
 );

CREATE SEQUENCE seq_discounts_id INCREMENT BY 1 START WITH 1;

INSERT INTO discounts VALUES
(nextval('seq_discounts_id'),'2011-03-12','2011-03-30',5),
(nextval('seq_discounts_id'),'2015-03-12','2015-03-30',10),(nextval('seq_discounts_id'),'2014-03-12','2014-03-30',50);

CREATE SEQUENCE seq_shop_id INCREMENT BY 1 START WITH 1;

CREATE TABLE shops ( 
	shop_id              integer  PRIMARY KEY DEFAULT nextval('seq_shop_id'),
	"location"           varchar(50) ,
	name                 varchar(100) not NULL,
	login			varchar(50) unique not NULL,
	"password"		varchar(200) not NULL
 );



INSERT INTO shops VALUES
(nextval('seq_shop_id'),'Krakow','sklep a','a','a'),
(nextval('seq_shop_id'),'Krakow','sklep b','b','b'),
(nextval('seq_shop_id'),'Warszawa','sklep c','c','c');


CREATE TABLE attributes ( 
	attribute_id         integer  PRIMARY KEY ,
	name                 varchar(100) not NULL,
	category_id          integer not NULL,
	unit                 varchar(50),
	CONSTRAINT uni_att UNIQUE (name, category_id),
	CONSTRAINT fk_attribute_categories FOREIGN KEY ( category_id ) REFERENCES categories( category_id ) on delete cascade
 );

CREATE SEQUENCE seq_attribute_id INCREMENT BY 1 START WITH 1;

INSERT INTO attributes VALUES
(nextval('seq_attribute_id'), 'material',1, null),
(nextval('seq_attribute_id'), 'kolor',1, null),
(nextval('seq_attribute_id'), 'ile drzwi',3, null),
(nextval('seq_attribute_id'), 'pojemnosc',7, 'ml');

CREATE TABLE customers_shops ( 
	customer_id          integer not NULL,
	shop_id              integer not NULL,
	rating               integer not NULL,
	CONSTRAINT uni_cus_shop UNIQUE(customer_id,shop_id),
	CONSTRAINT fk_customers_shops_customers FOREIGN KEY ( customer_id ) REFERENCES customers( customer_id )  on delete cascade,
	CONSTRAINT fk_customers_shops_shops FOREIGN KEY ( shop_id ) REFERENCES shops( shop_id ),
	CHECK (rating<=5 AND rating>=0) on delete cascade
 );

INSERT INTO customers_shops VALUES
(1,1,1),(1,2,4),(2,3,4),(2,1,4);

CREATE SEQUENCE seq_product_id INCREMENT BY 1 START WITH 1;

CREATE TABLE products ( 
	product_id           integer  PRIMARY KEY default nextval('seq_product_id'),
	name                 varchar(100) not NULL unique,
	description          varchar(200),
	category_id          integer,
	CONSTRAINT fk_products_categories FOREIGN KEY ( category_id ) REFERENCES categories( category_id ) on delete cascade
 );


INSERT INTO products VALUES
(nextval('seq_product_id'), 'krzeslo a',null,3),
(nextval('seq_product_id'), 'krzeslo b',null,3),
(nextval('seq_product_id'), 'szafa a',null,4),
(nextval('seq_product_id'), 'szafka kuchenna a',null,5),
(nextval('seq_product_id'), 'jablko',null,6),
(nextval('seq_product_id'), 'sok',null,7),
(nextval('seq_product_id'), 'wino',null,8),
(nextval('seq_product_id'), 'piwo',null,8),
(nextval('seq_product_id'), 'szafka kuchenna b',null,5),
(nextval('seq_product_id'),'krzeslo 0',null,3),
(nextval('seq_product_id'),'krzeslo 1',null,3),
(nextval('seq_product_id'),'krzeslo 2',null,3),
(nextval('seq_product_id'),'krzeslo 3',null,3),
(nextval('seq_product_id'),'krzeslo 4',null,3),
(nextval('seq_product_id'),'krzeslo 5',null,3),
(nextval('seq_product_id'),'krzeslo 6',null,3),
(nextval('seq_product_id'),'krzeslo 7',null,3),
(nextval('seq_product_id'),'krzeslo 8',null,3),
(nextval('seq_product_id'),'krzeslo 9',null,3),
(nextval('seq_product_id'),'krzeslo 10',null,3),
(nextval('seq_product_id'),'krzeslo 11',null,3),
(nextval('seq_product_id'),'krzeslo 12',null,3),
(nextval('seq_product_id'),'krzeslo 13',null,3),
(nextval('seq_product_id'),'krzeslo 14',null,3),
(nextval('seq_product_id'),'krzeslo 15',null,3),
(nextval('seq_product_id'),'krzeslo 16',null,3),
(nextval('seq_product_id'),'krzeslo 17',null,3),
(nextval('seq_product_id'),'krzeslo 18',null,3),
(nextval('seq_product_id'),'krzeslo 19',null,3),
(nextval('seq_product_id'),'krzeslo 20',null,3),
(nextval('seq_product_id'),'krzeslo 21',null,3),
(nextval('seq_product_id'),'krzeslo 22',null,3),
(nextval('seq_product_id'),'krzeslo 23',null,3),
(nextval('seq_product_id'),'krzeslo 24',null,3),
(nextval('seq_product_id'),'krzeslo 25',null,3),
(nextval('seq_product_id'),'krzeslo 26',null,3),
(nextval('seq_product_id'),'krzeslo 27',null,3),
(nextval('seq_product_id'),'krzeslo 28',null,3),
(nextval('seq_product_id'),'krzeslo 29',null,3),
(nextval('seq_product_id'),'krzeslo 30',null,3),
(nextval('seq_product_id'),'krzeslo 31',null,3),
(nextval('seq_product_id'),'krzeslo 32',null,3),
(nextval('seq_product_id'),'krzeslo 33',null,3),
(nextval('seq_product_id'),'krzeslo 34',null,3),
(nextval('seq_product_id'),'krzeslo 35',null,3),
(nextval('seq_product_id'),'krzeslo 36',null,3),
(nextval('seq_product_id'),'krzeslo 37',null,3),
(nextval('seq_product_id'),'krzeslo 38',null,3),
(nextval('seq_product_id'),'krzeslo 39',null,3),
(nextval('seq_product_id'),'krzeslo 40',null,3),
(nextval('seq_product_id'),'krzeslo 41',null,3),
(nextval('seq_product_id'),'krzeslo 42',null,3),
(nextval('seq_product_id'),'krzeslo 43',null,3),
(nextval('seq_product_id'),'krzeslo 44',null,3),
(nextval('seq_product_id'),'krzeslo 45',null,3),
(nextval('seq_product_id'),'krzeslo 46',null,3),
(nextval('seq_product_id'),'krzeslo 47',null,3),
(nextval('seq_product_id'),'krzeslo 48',null,3),
(nextval('seq_product_id'),'krzeslo 49',null,3),
(nextval('seq_product_id'),'krzeslo 50',null,3),
(nextval('seq_product_id'),'krzeslo 51',null,3),
(nextval('seq_product_id'),'krzeslo 52',null,3),
(nextval('seq_product_id'),'krzeslo 53',null,3),
(nextval('seq_product_id'),'krzeslo 54',null,3),
(nextval('seq_product_id'),'krzeslo 55',null,3),
(nextval('seq_product_id'),'krzeslo 56',null,3),
(nextval('seq_product_id'),'krzeslo 57',null,3),
(nextval('seq_product_id'),'krzeslo 58',null,3),
(nextval('seq_product_id'),'krzeslo 59',null,3),
(nextval('seq_product_id'),'krzeslo 60',null,3),
(nextval('seq_product_id'),'krzeslo 61',null,3),
(nextval('seq_product_id'),'krzeslo 62',null,3),
(nextval('seq_product_id'),'krzeslo 63',null,3),
(nextval('seq_product_id'),'krzeslo 64',null,3),
(nextval('seq_product_id'),'krzeslo 65',null,3),
(nextval('seq_product_id'),'krzeslo 66',null,3),
(nextval('seq_product_id'),'krzeslo 67',null,3),
(nextval('seq_product_id'),'krzeslo 68',null,3),
(nextval('seq_product_id'),'krzeslo 69',null,3),
(nextval('seq_product_id'),'krzeslo 70',null,3),
(nextval('seq_product_id'),'krzeslo 71',null,3),
(nextval('seq_product_id'),'krzeslo 72',null,3),
(nextval('seq_product_id'),'krzeslo 73',null,3),
(nextval('seq_product_id'),'krzeslo 74',null,3),
(nextval('seq_product_id'),'krzeslo 75',null,3),
(nextval('seq_product_id'),'krzeslo 76',null,3),
(nextval('seq_product_id'),'krzeslo 77',null,3),
(nextval('seq_product_id'),'krzeslo 78',null,3),
(nextval('seq_product_id'),'krzeslo 79',null,3),
(nextval('seq_product_id'),'krzeslo 80',null,3),
(nextval('seq_product_id'),'krzeslo 81',null,3),
(nextval('seq_product_id'),'krzeslo 82',null,3),
(nextval('seq_product_id'),'krzeslo 83',null,3),
(nextval('seq_product_id'),'krzeslo 84',null,3),
(nextval('seq_product_id'),'krzeslo 85',null,3),
(nextval('seq_product_id'),'krzeslo 86',null,3),
(nextval('seq_product_id'),'krzeslo 87',null,3),
(nextval('seq_product_id'),'krzeslo 88',null,3),
(nextval('seq_product_id'),'krzeslo 89',null,3),
(nextval('seq_product_id'),'krzeslo 90',null,3),
(nextval('seq_product_id'),'krzeslo 91',null,3),
(nextval('seq_product_id'),'krzeslo 92',null,3),
(nextval('seq_product_id'),'krzeslo 93',null,3),
(nextval('seq_product_id'),'krzeslo 94',null,3),
(nextval('seq_product_id'),'krzeslo 95',null,3),
(nextval('seq_product_id'),'krzeslo 96',null,3),
(nextval('seq_product_id'),'krzeslo 97',null,3),
(nextval('seq_product_id'),'krzeslo 98',null,3),
(nextval('seq_product_id'),'krzeslo 99',null,3),
(nextval('seq_product_id'),'krzeslo 100',null,3),
(nextval('seq_product_id'),'krzeslo 101',null,3),
(nextval('seq_product_id'),'krzeslo 102',null,3),
(nextval('seq_product_id'),'krzeslo 103',null,3),
(nextval('seq_product_id'),'krzeslo 104',null,3),
(nextval('seq_product_id'),'krzeslo 105',null,3),
(nextval('seq_product_id'),'krzeslo 106',null,3),
(nextval('seq_product_id'),'krzeslo 107',null,3),
(nextval('seq_product_id'),'krzeslo 108',null,3),
(nextval('seq_product_id'),'krzeslo 109',null,3),
(nextval('seq_product_id'),'krzeslo 110',null,3),
(nextval('seq_product_id'),'krzeslo 111',null,3),
(nextval('seq_product_id'),'krzeslo 112',null,3),
(nextval('seq_product_id'),'krzeslo 113',null,3),
(nextval('seq_product_id'),'krzeslo 114',null,3),
(nextval('seq_product_id'),'krzeslo 115',null,3),
(nextval('seq_product_id'),'krzeslo 116',null,3),
(nextval('seq_product_id'),'krzeslo 117',null,3),
(nextval('seq_product_id'),'krzeslo 118',null,3),
(nextval('seq_product_id'),'krzeslo 119',null,3),
(nextval('seq_product_id'),'krzeslo 120',null,3),
(nextval('seq_product_id'),'krzeslo 121',null,3),
(nextval('seq_product_id'),'krzeslo 122',null,3),
(nextval('seq_product_id'),'krzeslo 123',null,3),
(nextval('seq_product_id'),'krzeslo 124',null,3),
(nextval('seq_product_id'),'krzeslo 125',null,3),
(nextval('seq_product_id'),'krzeslo 126',null,3),
(nextval('seq_product_id'),'krzeslo 127',null,3),
(nextval('seq_product_id'),'krzeslo 128',null,3),
(nextval('seq_product_id'),'krzeslo 129',null,3),
(nextval('seq_product_id'),'krzeslo 130',null,3),
(nextval('seq_product_id'),'krzeslo 131',null,3),
(nextval('seq_product_id'),'krzeslo 132',null,3),
(nextval('seq_product_id'),'krzeslo 133',null,3),
(nextval('seq_product_id'),'krzeslo 134',null,3),
(nextval('seq_product_id'),'krzeslo 135',null,3),
(nextval('seq_product_id'),'krzeslo 136',null,3),
(nextval('seq_product_id'),'krzeslo 137',null,3),
(nextval('seq_product_id'),'krzeslo 138',null,3),
(nextval('seq_product_id'),'krzeslo 139',null,3),
(nextval('seq_product_id'),'krzeslo 140',null,3),
(nextval('seq_product_id'),'krzeslo 141',null,3),
(nextval('seq_product_id'),'krzeslo 142',null,3),
(nextval('seq_product_id'),'krzeslo 143',null,3),
(nextval('seq_product_id'),'krzeslo 144',null,3),
(nextval('seq_product_id'),'krzeslo 145',null,3),
(nextval('seq_product_id'),'krzeslo 146',null,3),
(nextval('seq_product_id'),'krzeslo 147',null,3),
(nextval('seq_product_id'),'krzeslo 148',null,3),
(nextval('seq_product_id'),'krzeslo 149',null,3),
(nextval('seq_product_id'),'krzeslo 150',null,3),
(nextval('seq_product_id'),'krzeslo 151',null,3),
(nextval('seq_product_id'),'krzeslo 152',null,3),
(nextval('seq_product_id'),'krzeslo 153',null,3),
(nextval('seq_product_id'),'krzeslo 154',null,3),
(nextval('seq_product_id'),'krzeslo 155',null,3),
(nextval('seq_product_id'),'krzeslo 156',null,3),
(nextval('seq_product_id'),'krzeslo 157',null,3),
(nextval('seq_product_id'),'krzeslo 158',null,3),
(nextval('seq_product_id'),'krzeslo 159',null,3),
(nextval('seq_product_id'),'krzeslo 160',null,3),
(nextval('seq_product_id'),'krzeslo 161',null,3),
(nextval('seq_product_id'),'krzeslo 162',null,3),
(nextval('seq_product_id'),'krzeslo 163',null,3),
(nextval('seq_product_id'),'krzeslo 164',null,3),
(nextval('seq_product_id'),'krzeslo 165',null,3),
(nextval('seq_product_id'),'krzeslo 166',null,3),
(nextval('seq_product_id'),'krzeslo 167',null,3),
(nextval('seq_product_id'),'krzeslo 168',null,3),
(nextval('seq_product_id'),'krzeslo 169',null,3),
(nextval('seq_product_id'),'krzeslo 170',null,3),
(nextval('seq_product_id'),'krzeslo 171',null,3),
(nextval('seq_product_id'),'krzeslo 172',null,3),
(nextval('seq_product_id'),'krzeslo 173',null,3),
(nextval('seq_product_id'),'krzeslo 174',null,3),
(nextval('seq_product_id'),'krzeslo 175',null,3),
(nextval('seq_product_id'),'krzeslo 176',null,3),
(nextval('seq_product_id'),'krzeslo 177',null,3),
(nextval('seq_product_id'),'krzeslo 178',null,3),
(nextval('seq_product_id'),'krzeslo 179',null,3),
(nextval('seq_product_id'),'krzeslo 180',null,3),
(nextval('seq_product_id'),'krzeslo 181',null,3),
(nextval('seq_product_id'),'krzeslo 182',null,3),
(nextval('seq_product_id'),'krzeslo 183',null,3),
(nextval('seq_product_id'),'krzeslo 184',null,3),
(nextval('seq_product_id'),'krzeslo 185',null,3),
(nextval('seq_product_id'),'krzeslo 186',null,3),
(nextval('seq_product_id'),'krzeslo 187',null,3),
(nextval('seq_product_id'),'krzeslo 188',null,3),
(nextval('seq_product_id'),'krzeslo 189',null,3),
(nextval('seq_product_id'),'krzeslo 190',null,3),
(nextval('seq_product_id'),'krzeslo 191',null,3),
(nextval('seq_product_id'),'krzeslo 192',null,3),
(nextval('seq_product_id'),'krzeslo 193',null,3),
(nextval('seq_product_id'),'krzeslo 194',null,3),
(nextval('seq_product_id'),'krzeslo 195',null,3),
(nextval('seq_product_id'),'krzeslo 196',null,3),
(nextval('seq_product_id'),'krzeslo 197',null,3),
(nextval('seq_product_id'),'krzeslo 198',null,3),
(nextval('seq_product_id'),'krzeslo 199',null,3),
(nextval('seq_product_id'),'krzeslo 200',null,3),
(nextval('seq_product_id'),'krzeslo 201',null,3),
(nextval('seq_product_id'),'krzeslo 202',null,3),
(nextval('seq_product_id'),'krzeslo 203',null,3),
(nextval('seq_product_id'),'krzeslo 204',null,3),
(nextval('seq_product_id'),'krzeslo 205',null,3),
(nextval('seq_product_id'),'krzeslo 206',null,3),
(nextval('seq_product_id'),'krzeslo 207',null,3),
(nextval('seq_product_id'),'krzeslo 208',null,3),
(nextval('seq_product_id'),'krzeslo 209',null,3),
(nextval('seq_product_id'),'krzeslo 210',null,3),
(nextval('seq_product_id'),'krzeslo 211',null,3),
(nextval('seq_product_id'),'krzeslo 212',null,3),
(nextval('seq_product_id'),'krzeslo 213',null,3),
(nextval('seq_product_id'),'krzeslo 214',null,3),
(nextval('seq_product_id'),'krzeslo 215',null,3),
(nextval('seq_product_id'),'krzeslo 216',null,3),
(nextval('seq_product_id'),'krzeslo 217',null,3),
(nextval('seq_product_id'),'krzeslo 218',null,3),
(nextval('seq_product_id'),'krzeslo 219',null,3),
(nextval('seq_product_id'),'krzeslo 220',null,3),
(nextval('seq_product_id'),'krzeslo 221',null,3),
(nextval('seq_product_id'),'krzeslo 222',null,3),
(nextval('seq_product_id'),'krzeslo 223',null,3),
(nextval('seq_product_id'),'krzeslo 224',null,3),
(nextval('seq_product_id'),'krzeslo 225',null,3),
(nextval('seq_product_id'),'krzeslo 226',null,3),
(nextval('seq_product_id'),'krzeslo 227',null,3),
(nextval('seq_product_id'),'krzeslo 228',null,3),
(nextval('seq_product_id'),'krzeslo 229',null,3),
(nextval('seq_product_id'),'krzeslo 230',null,3),
(nextval('seq_product_id'),'krzeslo 231',null,3),
(nextval('seq_product_id'),'krzeslo 232',null,3),
(nextval('seq_product_id'),'krzeslo 233',null,3),
(nextval('seq_product_id'),'krzeslo 234',null,3),
(nextval('seq_product_id'),'krzeslo 235',null,3),
(nextval('seq_product_id'),'krzeslo 236',null,3),
(nextval('seq_product_id'),'krzeslo 237',null,3),
(nextval('seq_product_id'),'krzeslo 238',null,3),
(nextval('seq_product_id'),'krzeslo 239',null,3),
(nextval('seq_product_id'),'krzeslo 240',null,3),
(nextval('seq_product_id'),'krzeslo 241',null,3),
(nextval('seq_product_id'),'krzeslo 242',null,3),
(nextval('seq_product_id'),'krzeslo 243',null,3),
(nextval('seq_product_id'),'krzeslo 244',null,3),
(nextval('seq_product_id'),'krzeslo 245',null,3),
(nextval('seq_product_id'),'krzeslo 246',null,3),
(nextval('seq_product_id'),'krzeslo 247',null,3),
(nextval('seq_product_id'),'krzeslo 248',null,3),
(nextval('seq_product_id'),'krzeslo 249',null,3),
(nextval('seq_product_id'),'krzeslo 250',null,3),
(nextval('seq_product_id'),'krzeslo 251',null,3),
(nextval('seq_product_id'),'krzeslo 252',null,3),
(nextval('seq_product_id'),'krzeslo 253',null,3),
(nextval('seq_product_id'),'krzeslo 254',null,3),
(nextval('seq_product_id'),'krzeslo 255',null,3),
(nextval('seq_product_id'),'krzeslo 256',null,3),
(nextval('seq_product_id'),'krzeslo 257',null,3),
(nextval('seq_product_id'),'krzeslo 258',null,3),
(nextval('seq_product_id'),'krzeslo 259',null,3),
(nextval('seq_product_id'),'krzeslo 260',null,3),
(nextval('seq_product_id'),'krzeslo 261',null,3),
(nextval('seq_product_id'),'krzeslo 262',null,3),
(nextval('seq_product_id'),'krzeslo 263',null,3),
(nextval('seq_product_id'),'krzeslo 264',null,3),
(nextval('seq_product_id'),'krzeslo 265',null,3),
(nextval('seq_product_id'),'krzeslo 266',null,3),
(nextval('seq_product_id'),'krzeslo 267',null,3),
(nextval('seq_product_id'),'krzeslo 268',null,3),
(nextval('seq_product_id'),'krzeslo 269',null,3),
(nextval('seq_product_id'),'krzeslo 270',null,3),
(nextval('seq_product_id'),'krzeslo 271',null,3),
(nextval('seq_product_id'),'krzeslo 272',null,3),
(nextval('seq_product_id'),'krzeslo 273',null,3),
(nextval('seq_product_id'),'krzeslo 274',null,3),
(nextval('seq_product_id'),'krzeslo 275',null,3),
(nextval('seq_product_id'),'krzeslo 276',null,3),
(nextval('seq_product_id'),'krzeslo 277',null,3),
(nextval('seq_product_id'),'krzeslo 278',null,3),
(nextval('seq_product_id'),'krzeslo 279',null,3),
(nextval('seq_product_id'),'krzeslo 280',null,3),
(nextval('seq_product_id'),'krzeslo 281',null,3),
(nextval('seq_product_id'),'krzeslo 282',null,3),
(nextval('seq_product_id'),'krzeslo 283',null,3),
(nextval('seq_product_id'),'krzeslo 284',null,3),
(nextval('seq_product_id'),'krzeslo 285',null,3),
(nextval('seq_product_id'),'krzeslo 286',null,3),
(nextval('seq_product_id'),'krzeslo 287',null,3),
(nextval('seq_product_id'),'krzeslo 288',null,3),
(nextval('seq_product_id'),'krzeslo 289',null,3),
(nextval('seq_product_id'),'krzeslo 290',null,3),
(nextval('seq_product_id'),'krzeslo 291',null,3),
(nextval('seq_product_id'),'krzeslo 292',null,3),
(nextval('seq_product_id'),'krzeslo 293',null,3),
(nextval('seq_product_id'),'krzeslo 294',null,3),
(nextval('seq_product_id'),'krzeslo 295',null,3),
(nextval('seq_product_id'),'krzeslo 296',null,3),
(nextval('seq_product_id'),'krzeslo 297',null,3),
(nextval('seq_product_id'),'krzeslo 298',null,3),
(nextval('seq_product_id'),'krzeslo 299',null,3),
(nextval('seq_product_id'),'krzeslo 300',null,3),
(nextval('seq_product_id'),'krzeslo 301',null,3),
(nextval('seq_product_id'),'krzeslo 302',null,3),
(nextval('seq_product_id'),'krzeslo 303',null,3),
(nextval('seq_product_id'),'krzeslo 304',null,3),
(nextval('seq_product_id'),'krzeslo 305',null,3),
(nextval('seq_product_id'),'krzeslo 306',null,3),
(nextval('seq_product_id'),'krzeslo 307',null,3),
(nextval('seq_product_id'),'krzeslo 308',null,3),
(nextval('seq_product_id'),'krzeslo 309',null,3),
(nextval('seq_product_id'),'krzeslo 310',null,3),
(nextval('seq_product_id'),'krzeslo 311',null,3),
(nextval('seq_product_id'),'krzeslo 312',null,3),
(nextval('seq_product_id'),'krzeslo 313',null,3),
(nextval('seq_product_id'),'krzeslo 314',null,3),
(nextval('seq_product_id'),'krzeslo 315',null,3),
(nextval('seq_product_id'),'krzeslo 316',null,3),
(nextval('seq_product_id'),'krzeslo 317',null,3),
(nextval('seq_product_id'),'krzeslo 318',null,3),
(nextval('seq_product_id'),'krzeslo 319',null,3),
(nextval('seq_product_id'),'krzeslo 320',null,3),
(nextval('seq_product_id'),'krzeslo 321',null,3),
(nextval('seq_product_id'),'krzeslo 322',null,3),
(nextval('seq_product_id'),'krzeslo 323',null,3),
(nextval('seq_product_id'),'krzeslo 324',null,3),
(nextval('seq_product_id'),'krzeslo 325',null,3),
(nextval('seq_product_id'),'krzeslo 326',null,3),
(nextval('seq_product_id'),'krzeslo 327',null,3),
(nextval('seq_product_id'),'krzeslo 328',null,3),
(nextval('seq_product_id'),'krzeslo 329',null,3),
(nextval('seq_product_id'),'krzeslo 330',null,3),
(nextval('seq_product_id'),'krzeslo 331',null,3),
(nextval('seq_product_id'),'krzeslo 332',null,3),
(nextval('seq_product_id'),'krzeslo 333',null,3),
(nextval('seq_product_id'),'krzeslo 334',null,3),
(nextval('seq_product_id'),'krzeslo 335',null,3),
(nextval('seq_product_id'),'krzeslo 336',null,3),
(nextval('seq_product_id'),'krzeslo 337',null,3),
(nextval('seq_product_id'),'krzeslo 338',null,3),
(nextval('seq_product_id'),'krzeslo 339',null,3),
(nextval('seq_product_id'),'krzeslo 340',null,3),
(nextval('seq_product_id'),'krzeslo 341',null,3),
(nextval('seq_product_id'),'krzeslo 342',null,3),
(nextval('seq_product_id'),'krzeslo 343',null,3),
(nextval('seq_product_id'),'krzeslo 344',null,3),
(nextval('seq_product_id'),'krzeslo 345',null,3),
(nextval('seq_product_id'),'krzeslo 346',null,3),
(nextval('seq_product_id'),'krzeslo 347',null,3),
(nextval('seq_product_id'),'krzeslo 348',null,3),
(nextval('seq_product_id'),'krzeslo 349',null,3),
(nextval('seq_product_id'),'krzeslo 350',null,3),
(nextval('seq_product_id'),'krzeslo 351',null,3),
(nextval('seq_product_id'),'krzeslo 352',null,3),
(nextval('seq_product_id'),'krzeslo 353',null,3),
(nextval('seq_product_id'),'krzeslo 354',null,3),
(nextval('seq_product_id'),'krzeslo 355',null,3),
(nextval('seq_product_id'),'krzeslo 356',null,3),
(nextval('seq_product_id'),'krzeslo 357',null,3),
(nextval('seq_product_id'),'krzeslo 358',null,3),
(nextval('seq_product_id'),'krzeslo 359',null,3),
(nextval('seq_product_id'),'krzeslo 360',null,3),
(nextval('seq_product_id'),'krzeslo 361',null,3),
(nextval('seq_product_id'),'krzeslo 362',null,3),
(nextval('seq_product_id'),'krzeslo 363',null,3),
(nextval('seq_product_id'),'krzeslo 364',null,3),
(nextval('seq_product_id'),'krzeslo 365',null,3),
(nextval('seq_product_id'),'krzeslo 366',null,3),
(nextval('seq_product_id'),'krzeslo 367',null,3),
(nextval('seq_product_id'),'krzeslo 368',null,3),
(nextval('seq_product_id'),'krzeslo 369',null,3),
(nextval('seq_product_id'),'krzeslo 370',null,3),
(nextval('seq_product_id'),'krzeslo 371',null,3),
(nextval('seq_product_id'),'krzeslo 372',null,3),
(nextval('seq_product_id'),'krzeslo 373',null,3),
(nextval('seq_product_id'),'krzeslo 374',null,3),
(nextval('seq_product_id'),'krzeslo 375',null,3),
(nextval('seq_product_id'),'krzeslo 376',null,3),
(nextval('seq_product_id'),'krzeslo 377',null,3),
(nextval('seq_product_id'),'krzeslo 378',null,3),
(nextval('seq_product_id'),'krzeslo 379',null,3),
(nextval('seq_product_id'),'krzeslo 380',null,3),
(nextval('seq_product_id'),'krzeslo 381',null,3),
(nextval('seq_product_id'),'krzeslo 382',null,3),
(nextval('seq_product_id'),'krzeslo 383',null,3),
(nextval('seq_product_id'),'krzeslo 384',null,3),
(nextval('seq_product_id'),'krzeslo 385',null,3),
(nextval('seq_product_id'),'krzeslo 386',null,3),
(nextval('seq_product_id'),'krzeslo 387',null,3),
(nextval('seq_product_id'),'krzeslo 388',null,3),
(nextval('seq_product_id'),'krzeslo 389',null,3),
(nextval('seq_product_id'),'krzeslo 390',null,3),
(nextval('seq_product_id'),'krzeslo 391',null,3),
(nextval('seq_product_id'),'krzeslo 392',null,3),
(nextval('seq_product_id'),'krzeslo 393',null,3),
(nextval('seq_product_id'),'krzeslo 394',null,3),
(nextval('seq_product_id'),'krzeslo 395',null,3),
(nextval('seq_product_id'),'krzeslo 396',null,3),
(nextval('seq_product_id'),'krzeslo 397',null,3),
(nextval('seq_product_id'),'krzeslo 398',null,3),
(nextval('seq_product_id'),'krzeslo 399',null,3),
(nextval('seq_product_id'),'krzeslo 400',null,3),
(nextval('seq_product_id'),'krzeslo 401',null,3),
(nextval('seq_product_id'),'krzeslo 402',null,3),
(nextval('seq_product_id'),'krzeslo 403',null,3),
(nextval('seq_product_id'),'krzeslo 404',null,3),
(nextval('seq_product_id'),'krzeslo 405',null,3),
(nextval('seq_product_id'),'krzeslo 406',null,3),
(nextval('seq_product_id'),'krzeslo 407',null,3),
(nextval('seq_product_id'),'krzeslo 408',null,3),
(nextval('seq_product_id'),'krzeslo 409',null,3),
(nextval('seq_product_id'),'krzeslo 410',null,3),
(nextval('seq_product_id'),'krzeslo 411',null,3),
(nextval('seq_product_id'),'krzeslo 412',null,3),
(nextval('seq_product_id'),'krzeslo 413',null,3),
(nextval('seq_product_id'),'krzeslo 414',null,3),
(nextval('seq_product_id'),'krzeslo 415',null,3),
(nextval('seq_product_id'),'krzeslo 416',null,3),
(nextval('seq_product_id'),'krzeslo 417',null,3),
(nextval('seq_product_id'),'krzeslo 418',null,3),
(nextval('seq_product_id'),'krzeslo 419',null,3),
(nextval('seq_product_id'),'krzeslo 420',null,3),
(nextval('seq_product_id'),'krzeslo 421',null,3),
(nextval('seq_product_id'),'krzeslo 422',null,3),
(nextval('seq_product_id'),'krzeslo 423',null,3),
(nextval('seq_product_id'),'krzeslo 424',null,3),
(nextval('seq_product_id'),'krzeslo 425',null,3),
(nextval('seq_product_id'),'krzeslo 426',null,3),
(nextval('seq_product_id'),'krzeslo 427',null,3),
(nextval('seq_product_id'),'krzeslo 428',null,3),
(nextval('seq_product_id'),'krzeslo 429',null,3),
(nextval('seq_product_id'),'krzeslo 430',null,3),
(nextval('seq_product_id'),'krzeslo 431',null,3),
(nextval('seq_product_id'),'krzeslo 432',null,3),
(nextval('seq_product_id'),'krzeslo 433',null,3),
(nextval('seq_product_id'),'krzeslo 434',null,3),
(nextval('seq_product_id'),'krzeslo 435',null,3),
(nextval('seq_product_id'),'krzeslo 436',null,3),
(nextval('seq_product_id'),'krzeslo 437',null,3),
(nextval('seq_product_id'),'krzeslo 438',null,3),
(nextval('seq_product_id'),'krzeslo 439',null,3),
(nextval('seq_product_id'),'krzeslo 440',null,3),
(nextval('seq_product_id'),'krzeslo 441',null,3),
(nextval('seq_product_id'),'krzeslo 442',null,3),
(nextval('seq_product_id'),'krzeslo 443',null,3),
(nextval('seq_product_id'),'krzeslo 444',null,3),
(nextval('seq_product_id'),'krzeslo 445',null,3),
(nextval('seq_product_id'),'krzeslo 446',null,3),
(nextval('seq_product_id'),'krzeslo 447',null,3),
(nextval('seq_product_id'),'krzeslo 448',null,3),
(nextval('seq_product_id'),'krzeslo 449',null,3),
(nextval('seq_product_id'),'krzeslo 450',null,3),
(nextval('seq_product_id'),'krzeslo 451',null,3),
(nextval('seq_product_id'),'krzeslo 452',null,3),
(nextval('seq_product_id'),'krzeslo 453',null,3),
(nextval('seq_product_id'),'krzeslo 454',null,3),
(nextval('seq_product_id'),'krzeslo 455',null,3),
(nextval('seq_product_id'),'krzeslo 456',null,3),
(nextval('seq_product_id'),'krzeslo 457',null,3),
(nextval('seq_product_id'),'krzeslo 458',null,3),
(nextval('seq_product_id'),'krzeslo 459',null,3),
(nextval('seq_product_id'),'krzeslo 460',null,3),
(nextval('seq_product_id'),'krzeslo 461',null,3),
(nextval('seq_product_id'),'krzeslo 462',null,3),
(nextval('seq_product_id'),'krzeslo 463',null,3),
(nextval('seq_product_id'),'krzeslo 464',null,3),
(nextval('seq_product_id'),'krzeslo 465',null,3),
(nextval('seq_product_id'),'krzeslo 466',null,3),
(nextval('seq_product_id'),'krzeslo 467',null,3),
(nextval('seq_product_id'),'krzeslo 468',null,3),
(nextval('seq_product_id'),'krzeslo 469',null,3),
(nextval('seq_product_id'),'krzeslo 470',null,3),
(nextval('seq_product_id'),'krzeslo 471',null,3),
(nextval('seq_product_id'),'krzeslo 472',null,3),
(nextval('seq_product_id'),'krzeslo 473',null,3),
(nextval('seq_product_id'),'krzeslo 474',null,3),
(nextval('seq_product_id'),'krzeslo 475',null,3),
(nextval('seq_product_id'),'krzeslo 476',null,3),
(nextval('seq_product_id'),'krzeslo 477',null,3),
(nextval('seq_product_id'),'krzeslo 478',null,3),
(nextval('seq_product_id'),'krzeslo 479',null,3),
(nextval('seq_product_id'),'krzeslo 480',null,3),
(nextval('seq_product_id'),'krzeslo 481',null,3),
(nextval('seq_product_id'),'krzeslo 482',null,3),
(nextval('seq_product_id'),'krzeslo 483',null,3),
(nextval('seq_product_id'),'krzeslo 484',null,3),
(nextval('seq_product_id'),'krzeslo 485',null,3),
(nextval('seq_product_id'),'krzeslo 486',null,3),
(nextval('seq_product_id'),'krzeslo 487',null,3),
(nextval('seq_product_id'),'krzeslo 488',null,3),
(nextval('seq_product_id'),'krzeslo 489',null,3),
(nextval('seq_product_id'),'krzeslo 490',null,3),
(nextval('seq_product_id'),'krzeslo 491',null,3),
(nextval('seq_product_id'),'krzeslo 492',null,3),
(nextval('seq_product_id'),'krzeslo 493',null,3),
(nextval('seq_product_id'),'krzeslo 494',null,3),
(nextval('seq_product_id'),'krzeslo 495',null,3),
(nextval('seq_product_id'),'krzeslo 496',null,3),
(nextval('seq_product_id'),'krzeslo 497',null,3),
(nextval('seq_product_id'),'krzeslo 498',null,3),
(nextval('seq_product_id'),'krzeslo 499',null,3),
(nextval('seq_product_id'),'krzeslo 500',null,3),
(nextval('seq_product_id'),'krzeslo 501',null,3),
(nextval('seq_product_id'),'krzeslo 502',null,3),
(nextval('seq_product_id'),'krzeslo 503',null,3),
(nextval('seq_product_id'),'krzeslo 504',null,3),
(nextval('seq_product_id'),'krzeslo 505',null,3),
(nextval('seq_product_id'),'krzeslo 506',null,3),
(nextval('seq_product_id'),'krzeslo 507',null,3),
(nextval('seq_product_id'),'krzeslo 508',null,3),
(nextval('seq_product_id'),'krzeslo 509',null,3),
(nextval('seq_product_id'),'krzeslo 510',null,3),
(nextval('seq_product_id'),'krzeslo 511',null,3),
(nextval('seq_product_id'),'krzeslo 512',null,3),
(nextval('seq_product_id'),'krzeslo 513',null,3),
(nextval('seq_product_id'),'krzeslo 514',null,3),
(nextval('seq_product_id'),'krzeslo 515',null,3),
(nextval('seq_product_id'),'krzeslo 516',null,3),
(nextval('seq_product_id'),'krzeslo 517',null,3),
(nextval('seq_product_id'),'krzeslo 518',null,3),
(nextval('seq_product_id'),'krzeslo 519',null,3),
(nextval('seq_product_id'),'krzeslo 520',null,3),
(nextval('seq_product_id'),'krzeslo 521',null,3),
(nextval('seq_product_id'),'krzeslo 522',null,3),
(nextval('seq_product_id'),'krzeslo 523',null,3),
(nextval('seq_product_id'),'krzeslo 524',null,3),
(nextval('seq_product_id'),'krzeslo 525',null,3),
(nextval('seq_product_id'),'krzeslo 526',null,3),
(nextval('seq_product_id'),'krzeslo 527',null,3),
(nextval('seq_product_id'),'krzeslo 528',null,3),
(nextval('seq_product_id'),'krzeslo 529',null,3),
(nextval('seq_product_id'),'krzeslo 530',null,3),
(nextval('seq_product_id'),'krzeslo 531',null,3),
(nextval('seq_product_id'),'krzeslo 532',null,3),
(nextval('seq_product_id'),'krzeslo 533',null,3),
(nextval('seq_product_id'),'krzeslo 534',null,3),
(nextval('seq_product_id'),'krzeslo 535',null,3),
(nextval('seq_product_id'),'krzeslo 536',null,3),
(nextval('seq_product_id'),'krzeslo 537',null,3),
(nextval('seq_product_id'),'krzeslo 538',null,3),
(nextval('seq_product_id'),'krzeslo 539',null,3),
(nextval('seq_product_id'),'krzeslo 540',null,3),
(nextval('seq_product_id'),'krzeslo 541',null,3),
(nextval('seq_product_id'),'krzeslo 542',null,3),
(nextval('seq_product_id'),'krzeslo 543',null,3),
(nextval('seq_product_id'),'krzeslo 544',null,3),
(nextval('seq_product_id'),'krzeslo 545',null,3),
(nextval('seq_product_id'),'krzeslo 546',null,3),
(nextval('seq_product_id'),'krzeslo 547',null,3),
(nextval('seq_product_id'),'krzeslo 548',null,3),
(nextval('seq_product_id'),'krzeslo 549',null,3),
(nextval('seq_product_id'),'krzeslo 550',null,3),
(nextval('seq_product_id'),'krzeslo 551',null,3),
(nextval('seq_product_id'),'krzeslo 552',null,3),
(nextval('seq_product_id'),'krzeslo 553',null,3),
(nextval('seq_product_id'),'krzeslo 554',null,3),
(nextval('seq_product_id'),'krzeslo 555',null,3),
(nextval('seq_product_id'),'krzeslo 556',null,3),
(nextval('seq_product_id'),'krzeslo 557',null,3),
(nextval('seq_product_id'),'krzeslo 558',null,3),
(nextval('seq_product_id'),'krzeslo 559',null,3),
(nextval('seq_product_id'),'krzeslo 560',null,3),
(nextval('seq_product_id'),'krzeslo 561',null,3),
(nextval('seq_product_id'),'krzeslo 562',null,3),
(nextval('seq_product_id'),'krzeslo 563',null,3),
(nextval('seq_product_id'),'krzeslo 564',null,3),
(nextval('seq_product_id'),'krzeslo 565',null,3),
(nextval('seq_product_id'),'krzeslo 566',null,3),
(nextval('seq_product_id'),'krzeslo 567',null,3),
(nextval('seq_product_id'),'krzeslo 568',null,3),
(nextval('seq_product_id'),'krzeslo 569',null,3),
(nextval('seq_product_id'),'krzeslo 570',null,3),
(nextval('seq_product_id'),'krzeslo 571',null,3),
(nextval('seq_product_id'),'krzeslo 572',null,3),
(nextval('seq_product_id'),'krzeslo 573',null,3),
(nextval('seq_product_id'),'krzeslo 574',null,3),
(nextval('seq_product_id'),'krzeslo 575',null,3),
(nextval('seq_product_id'),'krzeslo 576',null,3),
(nextval('seq_product_id'),'krzeslo 577',null,3),
(nextval('seq_product_id'),'krzeslo 578',null,3),
(nextval('seq_product_id'),'krzeslo 579',null,3),
(nextval('seq_product_id'),'krzeslo 580',null,3),
(nextval('seq_product_id'),'krzeslo 581',null,3),
(nextval('seq_product_id'),'krzeslo 582',null,3),
(nextval('seq_product_id'),'krzeslo 583',null,3),
(nextval('seq_product_id'),'krzeslo 584',null,3),
(nextval('seq_product_id'),'krzeslo 585',null,3),
(nextval('seq_product_id'),'krzeslo 586',null,3),
(nextval('seq_product_id'),'krzeslo 587',null,3),
(nextval('seq_product_id'),'krzeslo 588',null,3),
(nextval('seq_product_id'),'krzeslo 589',null,3),
(nextval('seq_product_id'),'krzeslo 590',null,3),
(nextval('seq_product_id'),'krzeslo 591',null,3),
(nextval('seq_product_id'),'krzeslo 592',null,3),
(nextval('seq_product_id'),'krzeslo 593',null,3),
(nextval('seq_product_id'),'krzeslo 594',null,3),
(nextval('seq_product_id'),'krzeslo 595',null,3),
(nextval('seq_product_id'),'krzeslo 596',null,3),
(nextval('seq_product_id'),'krzeslo 597',null,3),
(nextval('seq_product_id'),'krzeslo 598',null,3),
(nextval('seq_product_id'),'krzeslo 599',null,3),
(nextval('seq_product_id'),'krzeslo 600',null,3),
(nextval('seq_product_id'),'krzeslo 601',null,3),
(nextval('seq_product_id'),'krzeslo 602',null,3),
(nextval('seq_product_id'),'krzeslo 603',null,3),
(nextval('seq_product_id'),'krzeslo 604',null,3),
(nextval('seq_product_id'),'krzeslo 605',null,3),
(nextval('seq_product_id'),'krzeslo 606',null,3),
(nextval('seq_product_id'),'krzeslo 607',null,3),
(nextval('seq_product_id'),'krzeslo 608',null,3),
(nextval('seq_product_id'),'krzeslo 609',null,3),
(nextval('seq_product_id'),'krzeslo 610',null,3),
(nextval('seq_product_id'),'krzeslo 611',null,3),
(nextval('seq_product_id'),'krzeslo 612',null,3),
(nextval('seq_product_id'),'krzeslo 613',null,3),
(nextval('seq_product_id'),'krzeslo 614',null,3),
(nextval('seq_product_id'),'krzeslo 615',null,3),
(nextval('seq_product_id'),'krzeslo 616',null,3),
(nextval('seq_product_id'),'krzeslo 617',null,3),
(nextval('seq_product_id'),'krzeslo 618',null,3),
(nextval('seq_product_id'),'krzeslo 619',null,3),
(nextval('seq_product_id'),'krzeslo 620',null,3),
(nextval('seq_product_id'),'krzeslo 621',null,3),
(nextval('seq_product_id'),'krzeslo 622',null,3),
(nextval('seq_product_id'),'krzeslo 623',null,3),
(nextval('seq_product_id'),'krzeslo 624',null,3),
(nextval('seq_product_id'),'krzeslo 625',null,3),
(nextval('seq_product_id'),'krzeslo 626',null,3),
(nextval('seq_product_id'),'krzeslo 627',null,3),
(nextval('seq_product_id'),'krzeslo 628',null,3),
(nextval('seq_product_id'),'krzeslo 629',null,3),
(nextval('seq_product_id'),'krzeslo 630',null,3),
(nextval('seq_product_id'),'krzeslo 631',null,3),
(nextval('seq_product_id'),'krzeslo 632',null,3),
(nextval('seq_product_id'),'krzeslo 633',null,3),
(nextval('seq_product_id'),'krzeslo 634',null,3),
(nextval('seq_product_id'),'krzeslo 635',null,3),
(nextval('seq_product_id'),'krzeslo 636',null,3),
(nextval('seq_product_id'),'krzeslo 637',null,3),
(nextval('seq_product_id'),'krzeslo 638',null,3),
(nextval('seq_product_id'),'krzeslo 639',null,3),
(nextval('seq_product_id'),'krzeslo 640',null,3),
(nextval('seq_product_id'),'krzeslo 641',null,3),
(nextval('seq_product_id'),'krzeslo 642',null,3),
(nextval('seq_product_id'),'krzeslo 643',null,3),
(nextval('seq_product_id'),'krzeslo 644',null,3),
(nextval('seq_product_id'),'krzeslo 645',null,3),
(nextval('seq_product_id'),'krzeslo 646',null,3),
(nextval('seq_product_id'),'krzeslo 647',null,3),
(nextval('seq_product_id'),'krzeslo 648',null,3),
(nextval('seq_product_id'),'krzeslo 649',null,3),
(nextval('seq_product_id'),'krzeslo 650',null,3),
(nextval('seq_product_id'),'krzeslo 651',null,3),
(nextval('seq_product_id'),'krzeslo 652',null,3),
(nextval('seq_product_id'),'krzeslo 653',null,3),
(nextval('seq_product_id'),'krzeslo 654',null,3),
(nextval('seq_product_id'),'krzeslo 655',null,3),
(nextval('seq_product_id'),'krzeslo 656',null,3),
(nextval('seq_product_id'),'krzeslo 657',null,3),
(nextval('seq_product_id'),'krzeslo 658',null,3),
(nextval('seq_product_id'),'krzeslo 659',null,3),
(nextval('seq_product_id'),'krzeslo 660',null,3),
(nextval('seq_product_id'),'krzeslo 661',null,3),
(nextval('seq_product_id'),'krzeslo 662',null,3),
(nextval('seq_product_id'),'krzeslo 663',null,3),
(nextval('seq_product_id'),'krzeslo 664',null,3),
(nextval('seq_product_id'),'krzeslo 665',null,3),
(nextval('seq_product_id'),'krzeslo 666',null,3),
(nextval('seq_product_id'),'krzeslo 667',null,3),
(nextval('seq_product_id'),'krzeslo 668',null,3),
(nextval('seq_product_id'),'krzeslo 669',null,3),
(nextval('seq_product_id'),'krzeslo 670',null,3),
(nextval('seq_product_id'),'krzeslo 671',null,3),
(nextval('seq_product_id'),'krzeslo 672',null,3),
(nextval('seq_product_id'),'krzeslo 673',null,3),
(nextval('seq_product_id'),'krzeslo 674',null,3),
(nextval('seq_product_id'),'krzeslo 675',null,3),
(nextval('seq_product_id'),'krzeslo 676',null,3),
(nextval('seq_product_id'),'krzeslo 677',null,3),
(nextval('seq_product_id'),'krzeslo 678',null,3),
(nextval('seq_product_id'),'krzeslo 679',null,3),
(nextval('seq_product_id'),'krzeslo 680',null,3),
(nextval('seq_product_id'),'krzeslo 681',null,3),
(nextval('seq_product_id'),'krzeslo 682',null,3),
(nextval('seq_product_id'),'krzeslo 683',null,3),
(nextval('seq_product_id'),'krzeslo 684',null,3),
(nextval('seq_product_id'),'krzeslo 685',null,3),
(nextval('seq_product_id'),'krzeslo 686',null,3),
(nextval('seq_product_id'),'krzeslo 687',null,3),
(nextval('seq_product_id'),'krzeslo 688',null,3),
(nextval('seq_product_id'),'krzeslo 689',null,3),
(nextval('seq_product_id'),'krzeslo 690',null,3),
(nextval('seq_product_id'),'krzeslo 691',null,3),
(nextval('seq_product_id'),'krzeslo 692',null,3),
(nextval('seq_product_id'),'krzeslo 693',null,3),
(nextval('seq_product_id'),'krzeslo 694',null,3),
(nextval('seq_product_id'),'krzeslo 695',null,3),
(nextval('seq_product_id'),'krzeslo 696',null,3),
(nextval('seq_product_id'),'krzeslo 697',null,3),
(nextval('seq_product_id'),'krzeslo 698',null,3),
(nextval('seq_product_id'),'krzeslo 699',null,3),
(nextval('seq_product_id'),'krzeslo 700',null,3),
(nextval('seq_product_id'),'krzeslo 701',null,3),
(nextval('seq_product_id'),'krzeslo 702',null,3),
(nextval('seq_product_id'),'krzeslo 703',null,3),
(nextval('seq_product_id'),'krzeslo 704',null,3),
(nextval('seq_product_id'),'krzeslo 705',null,3),
(nextval('seq_product_id'),'krzeslo 706',null,3),
(nextval('seq_product_id'),'krzeslo 707',null,3),
(nextval('seq_product_id'),'krzeslo 708',null,3),
(nextval('seq_product_id'),'krzeslo 709',null,3),
(nextval('seq_product_id'),'krzeslo 710',null,3),
(nextval('seq_product_id'),'krzeslo 711',null,3),
(nextval('seq_product_id'),'krzeslo 712',null,3),
(nextval('seq_product_id'),'krzeslo 713',null,3),
(nextval('seq_product_id'),'krzeslo 714',null,3),
(nextval('seq_product_id'),'krzeslo 715',null,3),
(nextval('seq_product_id'),'krzeslo 716',null,3),
(nextval('seq_product_id'),'krzeslo 717',null,3),
(nextval('seq_product_id'),'krzeslo 718',null,3),
(nextval('seq_product_id'),'krzeslo 719',null,3),
(nextval('seq_product_id'),'krzeslo 720',null,3),
(nextval('seq_product_id'),'krzeslo 721',null,3),
(nextval('seq_product_id'),'krzeslo 722',null,3),
(nextval('seq_product_id'),'krzeslo 723',null,3),
(nextval('seq_product_id'),'krzeslo 724',null,3),
(nextval('seq_product_id'),'krzeslo 725',null,3),
(nextval('seq_product_id'),'krzeslo 726',null,3),
(nextval('seq_product_id'),'krzeslo 727',null,3),
(nextval('seq_product_id'),'krzeslo 728',null,3),
(nextval('seq_product_id'),'krzeslo 729',null,3),
(nextval('seq_product_id'),'krzeslo 730',null,3),
(nextval('seq_product_id'),'krzeslo 731',null,3),
(nextval('seq_product_id'),'krzeslo 732',null,3),
(nextval('seq_product_id'),'krzeslo 733',null,3),
(nextval('seq_product_id'),'krzeslo 734',null,3),
(nextval('seq_product_id'),'krzeslo 735',null,3),
(nextval('seq_product_id'),'krzeslo 736',null,3),
(nextval('seq_product_id'),'krzeslo 737',null,3),
(nextval('seq_product_id'),'krzeslo 738',null,3),
(nextval('seq_product_id'),'krzeslo 739',null,3),
(nextval('seq_product_id'),'krzeslo 740',null,3),
(nextval('seq_product_id'),'krzeslo 741',null,3),
(nextval('seq_product_id'),'krzeslo 742',null,3),
(nextval('seq_product_id'),'krzeslo 743',null,3),
(nextval('seq_product_id'),'krzeslo 744',null,3),
(nextval('seq_product_id'),'krzeslo 745',null,3),
(nextval('seq_product_id'),'krzeslo 746',null,3),
(nextval('seq_product_id'),'krzeslo 747',null,3),
(nextval('seq_product_id'),'krzeslo 748',null,3),
(nextval('seq_product_id'),'krzeslo 749',null,3),
(nextval('seq_product_id'),'krzeslo 750',null,3),
(nextval('seq_product_id'),'krzeslo 751',null,3),
(nextval('seq_product_id'),'krzeslo 752',null,3),
(nextval('seq_product_id'),'krzeslo 753',null,3),
(nextval('seq_product_id'),'krzeslo 754',null,3),
(nextval('seq_product_id'),'krzeslo 755',null,3),
(nextval('seq_product_id'),'krzeslo 756',null,3),
(nextval('seq_product_id'),'krzeslo 757',null,3),
(nextval('seq_product_id'),'krzeslo 758',null,3),
(nextval('seq_product_id'),'krzeslo 759',null,3),
(nextval('seq_product_id'),'krzeslo 760',null,3),
(nextval('seq_product_id'),'krzeslo 761',null,3),
(nextval('seq_product_id'),'krzeslo 762',null,3),
(nextval('seq_product_id'),'krzeslo 763',null,3),
(nextval('seq_product_id'),'krzeslo 764',null,3),
(nextval('seq_product_id'),'krzeslo 765',null,3),
(nextval('seq_product_id'),'krzeslo 766',null,3),
(nextval('seq_product_id'),'krzeslo 767',null,3),
(nextval('seq_product_id'),'krzeslo 768',null,3),
(nextval('seq_product_id'),'krzeslo 769',null,3),
(nextval('seq_product_id'),'krzeslo 770',null,3),
(nextval('seq_product_id'),'krzeslo 771',null,3),
(nextval('seq_product_id'),'krzeslo 772',null,3),
(nextval('seq_product_id'),'krzeslo 773',null,3),
(nextval('seq_product_id'),'krzeslo 774',null,3),
(nextval('seq_product_id'),'krzeslo 775',null,3),
(nextval('seq_product_id'),'krzeslo 776',null,3),
(nextval('seq_product_id'),'krzeslo 777',null,3),
(nextval('seq_product_id'),'krzeslo 778',null,3),
(nextval('seq_product_id'),'krzeslo 779',null,3),
(nextval('seq_product_id'),'krzeslo 780',null,3),
(nextval('seq_product_id'),'krzeslo 781',null,3),
(nextval('seq_product_id'),'krzeslo 782',null,3),
(nextval('seq_product_id'),'krzeslo 783',null,3),
(nextval('seq_product_id'),'krzeslo 784',null,3),
(nextval('seq_product_id'),'krzeslo 785',null,3),
(nextval('seq_product_id'),'krzeslo 786',null,3),
(nextval('seq_product_id'),'krzeslo 787',null,3),
(nextval('seq_product_id'),'krzeslo 788',null,3),
(nextval('seq_product_id'),'krzeslo 789',null,3),
(nextval('seq_product_id'),'krzeslo 790',null,3),
(nextval('seq_product_id'),'krzeslo 791',null,3),
(nextval('seq_product_id'),'krzeslo 792',null,3),
(nextval('seq_product_id'),'krzeslo 793',null,3),
(nextval('seq_product_id'),'krzeslo 794',null,3),
(nextval('seq_product_id'),'krzeslo 795',null,3),
(nextval('seq_product_id'),'krzeslo 796',null,3),
(nextval('seq_product_id'),'krzeslo 797',null,3),
(nextval('seq_product_id'),'krzeslo 798',null,3),
(nextval('seq_product_id'),'krzeslo 799',null,3),
(nextval('seq_product_id'),'krzeslo 800',null,3),
(nextval('seq_product_id'),'krzeslo 801',null,3),
(nextval('seq_product_id'),'krzeslo 802',null,3),
(nextval('seq_product_id'),'krzeslo 803',null,3),
(nextval('seq_product_id'),'krzeslo 804',null,3),
(nextval('seq_product_id'),'krzeslo 805',null,3),
(nextval('seq_product_id'),'krzeslo 806',null,3),
(nextval('seq_product_id'),'krzeslo 807',null,3),
(nextval('seq_product_id'),'krzeslo 808',null,3),
(nextval('seq_product_id'),'krzeslo 809',null,3),
(nextval('seq_product_id'),'krzeslo 810',null,3),
(nextval('seq_product_id'),'krzeslo 811',null,3),
(nextval('seq_product_id'),'krzeslo 812',null,3),
(nextval('seq_product_id'),'krzeslo 813',null,3),
(nextval('seq_product_id'),'krzeslo 814',null,3),
(nextval('seq_product_id'),'krzeslo 815',null,3),
(nextval('seq_product_id'),'krzeslo 816',null,3),
(nextval('seq_product_id'),'krzeslo 817',null,3),
(nextval('seq_product_id'),'krzeslo 818',null,3),
(nextval('seq_product_id'),'krzeslo 819',null,3),
(nextval('seq_product_id'),'krzeslo 820',null,3),
(nextval('seq_product_id'),'krzeslo 821',null,3),
(nextval('seq_product_id'),'krzeslo 822',null,3),
(nextval('seq_product_id'),'krzeslo 823',null,3),
(nextval('seq_product_id'),'krzeslo 824',null,3),
(nextval('seq_product_id'),'krzeslo 825',null,3),
(nextval('seq_product_id'),'krzeslo 826',null,3),
(nextval('seq_product_id'),'krzeslo 827',null,3),
(nextval('seq_product_id'),'krzeslo 828',null,3),
(nextval('seq_product_id'),'krzeslo 829',null,3),
(nextval('seq_product_id'),'krzeslo 830',null,3),
(nextval('seq_product_id'),'krzeslo 831',null,3),
(nextval('seq_product_id'),'krzeslo 832',null,3),
(nextval('seq_product_id'),'krzeslo 833',null,3),
(nextval('seq_product_id'),'krzeslo 834',null,3),
(nextval('seq_product_id'),'krzeslo 835',null,3),
(nextval('seq_product_id'),'krzeslo 836',null,3),
(nextval('seq_product_id'),'krzeslo 837',null,3),
(nextval('seq_product_id'),'krzeslo 838',null,3),
(nextval('seq_product_id'),'krzeslo 839',null,3),
(nextval('seq_product_id'),'krzeslo 840',null,3),
(nextval('seq_product_id'),'krzeslo 841',null,3),
(nextval('seq_product_id'),'krzeslo 842',null,3),
(nextval('seq_product_id'),'krzeslo 843',null,3),
(nextval('seq_product_id'),'krzeslo 844',null,3),
(nextval('seq_product_id'),'krzeslo 845',null,3),
(nextval('seq_product_id'),'krzeslo 846',null,3),
(nextval('seq_product_id'),'krzeslo 847',null,3),
(nextval('seq_product_id'),'krzeslo 848',null,3),
(nextval('seq_product_id'),'krzeslo 849',null,3),
(nextval('seq_product_id'),'krzeslo 850',null,3),
(nextval('seq_product_id'),'krzeslo 851',null,3),
(nextval('seq_product_id'),'krzeslo 852',null,3),
(nextval('seq_product_id'),'krzeslo 853',null,3),
(nextval('seq_product_id'),'krzeslo 854',null,3),
(nextval('seq_product_id'),'krzeslo 855',null,3),
(nextval('seq_product_id'),'krzeslo 856',null,3),
(nextval('seq_product_id'),'krzeslo 857',null,3),
(nextval('seq_product_id'),'krzeslo 858',null,3),
(nextval('seq_product_id'),'krzeslo 859',null,3),
(nextval('seq_product_id'),'krzeslo 860',null,3),
(nextval('seq_product_id'),'krzeslo 861',null,3),
(nextval('seq_product_id'),'krzeslo 862',null,3),
(nextval('seq_product_id'),'krzeslo 863',null,3),
(nextval('seq_product_id'),'krzeslo 864',null,3),
(nextval('seq_product_id'),'krzeslo 865',null,3),
(nextval('seq_product_id'),'krzeslo 866',null,3),
(nextval('seq_product_id'),'krzeslo 867',null,3),
(nextval('seq_product_id'),'krzeslo 868',null,3),
(nextval('seq_product_id'),'krzeslo 869',null,3),
(nextval('seq_product_id'),'krzeslo 870',null,3),
(nextval('seq_product_id'),'krzeslo 871',null,3),
(nextval('seq_product_id'),'krzeslo 872',null,3),
(nextval('seq_product_id'),'krzeslo 873',null,3),
(nextval('seq_product_id'),'krzeslo 874',null,3),
(nextval('seq_product_id'),'krzeslo 875',null,3),
(nextval('seq_product_id'),'krzeslo 876',null,3),
(nextval('seq_product_id'),'krzeslo 877',null,3),
(nextval('seq_product_id'),'krzeslo 878',null,3),
(nextval('seq_product_id'),'krzeslo 879',null,3),
(nextval('seq_product_id'),'krzeslo 880',null,3),
(nextval('seq_product_id'),'krzeslo 881',null,3),
(nextval('seq_product_id'),'krzeslo 882',null,3),
(nextval('seq_product_id'),'krzeslo 883',null,3),
(nextval('seq_product_id'),'krzeslo 884',null,3),
(nextval('seq_product_id'),'krzeslo 885',null,3),
(nextval('seq_product_id'),'krzeslo 886',null,3),
(nextval('seq_product_id'),'krzeslo 887',null,3),
(nextval('seq_product_id'),'krzeslo 888',null,3),
(nextval('seq_product_id'),'krzeslo 889',null,3),
(nextval('seq_product_id'),'krzeslo 890',null,3),
(nextval('seq_product_id'),'krzeslo 891',null,3),
(nextval('seq_product_id'),'krzeslo 892',null,3),
(nextval('seq_product_id'),'krzeslo 893',null,3),
(nextval('seq_product_id'),'krzeslo 894',null,3),
(nextval('seq_product_id'),'krzeslo 895',null,3),
(nextval('seq_product_id'),'krzeslo 896',null,3),
(nextval('seq_product_id'),'krzeslo 897',null,3),
(nextval('seq_product_id'),'krzeslo 898',null,3),
(nextval('seq_product_id'),'krzeslo 899',null,3),
(nextval('seq_product_id'),'krzeslo 900',null,3),
(nextval('seq_product_id'),'krzeslo 901',null,3),
(nextval('seq_product_id'),'krzeslo 902',null,3),
(nextval('seq_product_id'),'krzeslo 903',null,3),
(nextval('seq_product_id'),'krzeslo 904',null,3),
(nextval('seq_product_id'),'krzeslo 905',null,3),
(nextval('seq_product_id'),'krzeslo 906',null,3),
(nextval('seq_product_id'),'krzeslo 907',null,3),
(nextval('seq_product_id'),'krzeslo 908',null,3),
(nextval('seq_product_id'),'krzeslo 909',null,3),
(nextval('seq_product_id'),'krzeslo 910',null,3),
(nextval('seq_product_id'),'krzeslo 911',null,3),
(nextval('seq_product_id'),'krzeslo 912',null,3),
(nextval('seq_product_id'),'krzeslo 913',null,3),
(nextval('seq_product_id'),'krzeslo 914',null,3),
(nextval('seq_product_id'),'krzeslo 915',null,3),
(nextval('seq_product_id'),'krzeslo 916',null,3),
(nextval('seq_product_id'),'krzeslo 917',null,3),
(nextval('seq_product_id'),'krzeslo 918',null,3),
(nextval('seq_product_id'),'krzeslo 919',null,3),
(nextval('seq_product_id'),'krzeslo 920',null,3),
(nextval('seq_product_id'),'krzeslo 921',null,3),
(nextval('seq_product_id'),'krzeslo 922',null,3),
(nextval('seq_product_id'),'krzeslo 923',null,3),
(nextval('seq_product_id'),'krzeslo 924',null,3),
(nextval('seq_product_id'),'krzeslo 925',null,3),
(nextval('seq_product_id'),'krzeslo 926',null,3),
(nextval('seq_product_id'),'krzeslo 927',null,3),
(nextval('seq_product_id'),'krzeslo 928',null,3),
(nextval('seq_product_id'),'krzeslo 929',null,3),
(nextval('seq_product_id'),'krzeslo 930',null,3),
(nextval('seq_product_id'),'krzeslo 931',null,3),
(nextval('seq_product_id'),'krzeslo 932',null,3),
(nextval('seq_product_id'),'krzeslo 933',null,3),
(nextval('seq_product_id'),'krzeslo 934',null,3),
(nextval('seq_product_id'),'krzeslo 935',null,3),
(nextval('seq_product_id'),'krzeslo 936',null,3),
(nextval('seq_product_id'),'krzeslo 937',null,3),
(nextval('seq_product_id'),'krzeslo 938',null,3),
(nextval('seq_product_id'),'krzeslo 939',null,3),
(nextval('seq_product_id'),'krzeslo 940',null,3),
(nextval('seq_product_id'),'krzeslo 941',null,3),
(nextval('seq_product_id'),'krzeslo 942',null,3),
(nextval('seq_product_id'),'krzeslo 943',null,3),
(nextval('seq_product_id'),'krzeslo 944',null,3),
(nextval('seq_product_id'),'krzeslo 945',null,3),
(nextval('seq_product_id'),'krzeslo 946',null,3),
(nextval('seq_product_id'),'krzeslo 947',null,3),
(nextval('seq_product_id'),'krzeslo 948',null,3),
(nextval('seq_product_id'),'krzeslo 949',null,3),
(nextval('seq_product_id'),'krzeslo 950',null,3),
(nextval('seq_product_id'),'krzeslo 951',null,3),
(nextval('seq_product_id'),'krzeslo 952',null,3),
(nextval('seq_product_id'),'krzeslo 953',null,3),
(nextval('seq_product_id'),'krzeslo 954',null,3),
(nextval('seq_product_id'),'krzeslo 955',null,3),
(nextval('seq_product_id'),'krzeslo 956',null,3),
(nextval('seq_product_id'),'krzeslo 957',null,3),
(nextval('seq_product_id'),'krzeslo 958',null,3),
(nextval('seq_product_id'),'krzeslo 959',null,3),
(nextval('seq_product_id'),'krzeslo 960',null,3),
(nextval('seq_product_id'),'krzeslo 961',null,3),
(nextval('seq_product_id'),'krzeslo 962',null,3),
(nextval('seq_product_id'),'krzeslo 963',null,3),
(nextval('seq_product_id'),'krzeslo 964',null,3),
(nextval('seq_product_id'),'krzeslo 965',null,3),
(nextval('seq_product_id'),'krzeslo 966',null,3),
(nextval('seq_product_id'),'krzeslo 967',null,3),
(nextval('seq_product_id'),'krzeslo 968',null,3),
(nextval('seq_product_id'),'krzeslo 969',null,3),
(nextval('seq_product_id'),'krzeslo 970',null,3),
(nextval('seq_product_id'),'krzeslo 971',null,3),
(nextval('seq_product_id'),'krzeslo 972',null,3),
(nextval('seq_product_id'),'krzeslo 973',null,3),
(nextval('seq_product_id'),'krzeslo 974',null,3),
(nextval('seq_product_id'),'krzeslo 975',null,3),
(nextval('seq_product_id'),'krzeslo 976',null,3),
(nextval('seq_product_id'),'krzeslo 977',null,3),
(nextval('seq_product_id'),'krzeslo 978',null,3),
(nextval('seq_product_id'),'krzeslo 979',null,3),
(nextval('seq_product_id'),'krzeslo 980',null,3),
(nextval('seq_product_id'),'krzeslo 981',null,3),
(nextval('seq_product_id'),'krzeslo 982',null,3),
(nextval('seq_product_id'),'krzeslo 983',null,3),
(nextval('seq_product_id'),'krzeslo 984',null,3),
(nextval('seq_product_id'),'krzeslo 985',null,3),
(nextval('seq_product_id'),'krzeslo 986',null,3),
(nextval('seq_product_id'),'krzeslo 987',null,3),
(nextval('seq_product_id'),'krzeslo 988',null,3),
(nextval('seq_product_id'),'krzeslo 989',null,3),
(nextval('seq_product_id'),'krzeslo 990',null,3),
(nextval('seq_product_id'),'krzeslo 991',null,3),
(nextval('seq_product_id'),'krzeslo 992',null,3),
(nextval('seq_product_id'),'krzeslo 993',null,3),
(nextval('seq_product_id'),'krzeslo 994',null,3),
(nextval('seq_product_id'),'krzeslo 995',null,3),
(nextval('seq_product_id'),'krzeslo 996',null,3),
(nextval('seq_product_id'),'krzeslo 997',null,3),
(nextval('seq_product_id'),'krzeslo 998',null,3),
(nextval('seq_product_id'),'krzeslo 999',null,3);


CREATE TABLE attribute_product ( 
	product_id           integer not NULL,
	attribute_id         integer not NULL,
	"value"              varchar(100) not NULL,
	CONSTRAINT uni_att_pro UNIQUE (product_id,attribute_id),
	CONSTRAINT fk_attribute_product_attribute FOREIGN KEY ( attribute_id ) REFERENCES attributes( attribute_id ) on delete cascade,
	CONSTRAINT fk_attribute_product_products FOREIGN KEY ( product_id ) REFERENCES products( product_id )  on delete cascade
 );

INSERT INTO attribute_product VALUES
(1,1,'drewno'),
(1,2,'braz'),
(3,3,'3'),
(3,1,'drewno'),
(4,1,'metal'),
(4,3,'5'),
(6,4,'1000'),
(9,1,'metal');

CREATE SEQUENCE seq_sho_pro INCREMENT 1 START WITH 1;

CREATE TABLE shop_product ( 
	shop_product_id		integer PRIMARY KEY default nextval('seq_sho_pro'),
	shop_id              integer not NULL,
	product_id           integer not NULL,
	price                numeric(10,2) CHECK (price>=0) not NULL,
	CONSTRAINT uni_sho_pro UNIQUE (shop_id,product_id),
	CONSTRAINT fk_shop_product_discount_product FOREIGN KEY ( product_id ) REFERENCES products( product_id ) on delete cascade,
	CONSTRAINT fk_shop_product_shops FOREIGN KEY ( shop_id ) REFERENCES shops( shop_id ) on delete cascade 
 );



INSERT INTO shop_product VALUES
(nextval('seq_sho_pro'),1,1,3.5),
(nextval('seq_sho_pro'),2,1,5),
(nextval('seq_sho_pro'),3,1,7),
(nextval('seq_sho_pro'),1,2,3.5),
(nextval('seq_sho_pro'),1,3,3.5),
(nextval('seq_sho_pro'),2,4,3.5),
(nextval('seq_sho_pro'),1,5,3.5),
(nextval('seq_sho_pro'),1,6,3.5),
(nextval('seq_sho_pro'),3,7,3.5),
(nextval('seq_sho_pro'),3,8,3.5);


CREATE TABLE discount_shop_product ( 
	discount_id          integer not NULL,
	discount_product_id  integer not NULL,
	CONSTRAINT uni_dis_sho_pro UNIQUE (discount_id,discount_product_id),
	CONSTRAINT fk_discount_product_discounts FOREIGN KEY ( discount_id ) REFERENCES discounts( discount_id ) on delete cascade,
	CONSTRAINT fk_discount_product_shop_product FOREIGN KEY ( discount_product_id ) REFERENCES shop_product( shop_product_id ) on delete cascade
 );

INSERT INTO discount_shop_product VALUES
(1,1),(1,3),(2,5),(3,6),(2,4);


CREATE TABLE product_customer ( 
	product_id           integer  NOT NULL,
	customer_id          integer  NOT NULL,
	rating               integer  NOT NULL,
	CONSTRAINT uni_pro_cus UNIQUE (product_id,customer_id),
	CHECK (rating<=5 AND rating>=0),
	CONSTRAINT fk_product_customer_products FOREIGN KEY ( product_id ) REFERENCES products( product_id )  on delete cascade,
	CONSTRAINT fk_product_customer_customers FOREIGN KEY ( customer_id ) REFERENCES customers( customer_id ) on delete cascade
 );

INSERT INTO product_customer VALUES
(1,5,4),(1,3,2),(2,3,1),(2,5,1);







CREATE VIEW shop_ratings as select name,round(avg(rating),2) from customers_shops c join shops s on c.shop_id=s.shop_id group by s.shop_id;

CREATE VIEW product_ratings as select name,round(avg(rating),2) from product_customer c join products s on c.product_id=s.product_id group by s.product_id;

CREATE or replace FUNCTION attributes(id integer) returns table(atr integer) as
$$
DECLARE
current integer;
BEGIN
current=(select parent_category from categories where category_id=id);
if(current is null) then
	return query select attribute_id from attributes where category_id=id;
else
	return query select attribute_id from attributes where category_id=id union all select * from 
attributes(current);
end if;
END;
$$ LANGUAGE plpgsql;

CREATE or replace FUNCTION check_if_circuits() returns trigger as
$$
DECLARE
current integer;
max integer;
BEGIN
current=NEW.parent_category;
while(current is not null) loop
	current=(select parent_category from categories where category_id=current);
	if(current=NEW.category_id) then
		return NULL;
	end if;
end loop;
return NEW;
END;
$$ LANGUAGE plpgsql;

CREATE trigger prevent_circuits BEFORE INSERT OR UPDATE ON categories
FOR EACH ROW EXECUTE PROCEDURE check_if_circuits();

CREATE or replace FUNCTION prices(id numeric) returns table( shop integer, price_ numeric, amount_ numeric) as 
$$
BEGIN
return query select shop_id, price, amount from shop_product s where product_id=id;
end
$$ LANGUAGE plpgsql;

CREATE or replace function shop_rating(id integer) returns numeric as
$$
begin 
return (select round(avg(rating),2) from customers_shops c join shops s on c.shop_id=s.shop_id where shop_id=id);
end
$$ LANGUAGE plpgsql;

CREATE or replace function item_rating(id integer) returns numeric as
$$
begin 
return (select round(avg(rating),2) from product_customer c join products s on c.product_id=s.product_id where c.product_id=id and c.rating is not null);
end
$$ LANGUAGE plpgsql;

CREATE or replace function check_parents() returns trigger as
$$
declare
i record;
begin
for i in select * from attributes where attribute_id in (select * from attributes(NEW.category_id)) loop
	if(i.name=NEW.name) then
		return NULL;
	end if;
end loop;  
return NEW;
end
$$ LANGUAGE plpgsql;

CREATE trigger parents BEFORE INSERT OR UPDATE ON attributes
FOR EACH ROW EXECUTE PROCEDURE check_parents();

CREATE or replace function check_children() returns trigger as
$$
begin
delete from attributes where name=NEW.name and NEW.attribute_id in (select * from attributes(category_id)) and not NEW.attribute_id=attribute_id;
return NEW;
end
$$ LANGUAGE plpgsql;

CREATE trigger children AFTER INSERT OR UPDATE ON attributes
FOR EACH ROW EXECUTE PROCEDURE check_children();

create or replace function check_if_att() returns trigger as
$$
begin
if(NEW.attribute_id in (select * from attributes((select category_id from products where product_id=NEW.product_id)))) then
	return NEW;
end if;
return NULL;
end
$$ LANGUAGE plpgsql;

CREATE trigger att BEFORE INSERT OR UPDATE ON attribute_product
FOR EACH ROW EXECUTE PROCEDURE check_if_att();

create or replace function is_of_cat(cat varchar, par varchar) returns bool as $$
declare
parent integer ;
parentv varchar;
begin
if( cat=par) then
	return true;
end if;
parent=(select parent_category from categories where name=cat);
if(parent is null) then
	return false;
end if;
parentv=(select name from categories where category_id=parent);

return is_of_cat(parentv, par);
end;
$$ LANGUAGE plpgsql;



